### PR TITLE
Replace push_back() vs emplace_back() on axis/tests/cpp-tests and axis/core

### PR DESCRIPTION
**Pull request by aismann**
## Describe your changes
Replace push_back() vs emplace_back() on axis\tests\cpp-tests\Classes

## Issue ticket number and link
#762

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by aismann** [comment]
Finished.
Relaced on:
- core 
- test/cpp-tests/Classes

**Comment by aismann** [comment]
new emplace_back:
image

old push_back:
image

**Comment by aismann** [comment]
'extension' has also some potential:
Which folder should be NOT changed?
image

**Comment by halx99** [comment]
Let's merge core first

**Pull request merged**
