### PR TITLE
Fix to ensure Component::onEnter() is called

### PR DESCRIPTION
**Pull request by rh101**
## Describe your changes
If a component is added to a parent node after the parent `Node::onEnter()` has been called, then the `Component::onEnter()` would never be called. 

This fix ensures that if the component is added while the parent node is already running, then the `Component::onEnter()` is called.

## Issue ticket number and link
#866 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by DelinWorks** [comment]
maybe remove the `Component::onEnter` from `Node::onEnter` since your're calling `Component::onEnter` anyways when it gets added

for reference:
```
void Node::onEnter() {
    if (_componentContainer && !_componentContainer->isEmpty()) {
        _componentContainer->onEnter();
    }
}
```
portion should be removed.

**Comment by rh101** [comment]
> maybe remove the `Component::onEnter` from `Node::onEnter` since your're calling `Component::onEnter` anyways when it gets added

That code should not be removed, since it is still required.  Review the code carefully and you will see why.

The `Node::_running` flag is `false` until the end of the Node's onEnter() method, so if a component is added prior to `Node::onEnter()` being called, the only place `Component::onEnter()` will be called is in `Node::onEnter()`.  That's why the code is correct and should not be removed at all.

**Comment by DelinWorks** [comment]
I see..

**Comment by aismann** [comment]
Maybe a test (cpp-test) with different scenarios will be usefull too?

**Comment by rh101** [comment]
> Maybe a test (cpp-test) with different scenarios will be usefull too?

I don't see any way to test this, as the side effect of the original code is that `onEnter()` is never called, which would cause undesired behaviour in a component.  This fix simply ensures that `Component::onEnter()` is called regardless of when the component is added to the parent.

The sub-classes that inherit from `Component` and override `Component::onEnter()` are `Physics3DComponent`, `NavMeshObstacle` and `NavMeshAgent`, all of which would be buggy if they weren't added to the parent node prior to the parent node `Node::onEnter()`.  The current test cases cover them all, and the changes here have no impact on their operation.

**Pull request merged**
