### PR TITLE
Add custom localization support.

### PR DESCRIPTION
**Pull request by DelinWorks**
Refer to: #775

### CODE REVIEW

**Comment by askamn** [comment]
Looking good! Only thing that concerns me, is that now we have to store another 8 bytes per Label for the callback. But then again, if I look at CCLabel it has a thousand other fields lol, like all those bools which could have all been save in a single 64 bit integer (if that was that case, we could have also fit a new bool called _doLocalize there). 

Gosh, writing messages here to & fro is so weird on github. We need a discord server!

**Comment by rh101** [comment]
This implementation is not following conventional methods of how localization is handled.  

Correct me if I'm wrong in my understanding of how this implementation works:

`label->setString("Hello World");`

This goes through some filter to convert it to another language, so you're effectively using that string as the conversion key, which makes no sense, since that string you're passing in should be the actual text to be displayed.  The strings could be of any size, and you definitely don't want to be using that string in whatever the base language is (ie. EN) as the key.

The purpose of the label is to display text, not to modify it in any way, and that string should not be treated as a key to lookup text for other languages.

If that is how this implementation works, then I do not agree with it at all.

The localization implementation should be completely separate from the label, and and it's as simple as this (where `l10n` is the localization method or similar):

`label->setString(l10n('HELLO_WORD"));`

This would also have the effect of allowing you to look up the text in all languages by simply searching for that key.

**Comment by DelinWorks** [comment]
This implementation is correct, and as I stated above ^ it's just a test to show that the filter works, it only gets called if the pointer to that filter handler is not null, also the filter function just gets called if setString is called, that just gives the ability to automatically make the function deal with the passed values instead, and to ease the workflow of setting strings. and that's why I think this implementation is correct.

**Comment by rh101** [comment]
> There are instances where projects have a lot of lines of code where `setString` is used.. 

The frequency of `setString` should not be the deciding factor on how to implement this functionality, and in this instance, all setString code would need to be updated regardless in order to add the filter.   This implementation is effectively changing the meaning of `setString`.  

> You don't want to go to every line of every label and set it to `setStringLocalized` inorder to modify it

You would definitely would want to go through every call to `setString` to add localization support, because then you're making your intention clear in the source code.

Even if a method like `setLocalizedString` is implemented, it would need to be different to `setString`, for instance:

`setLocalizedString(std::string key)` which would make its intention clear, that you're passing a key, not the string to be displayed, and then that setLocalizedString would do the conversion, and then call `setString` with the localized text.

Now, while something like `setLocalizedString` would be helpful, it's still polluting the label class with code that doesn't actually have anything to do with the label.  This is a text conversion issue, not a label issue.

**Comment by DelinWorks** [comment]
how about adding a comment to `setString` that it has 2 abilities? besides that function is useful as it's just a filterer and that's it, it's like you're overriding `setString`

**Comment by rh101** [comment]
> how about adding a comment to `setString` that it has 2 abilities? besides, that function is useful as it's just a filterer and that's it, it's like you're overriding `setString`

I do really understand where you're coming from regarding this issue, in that you want to make it easier on developers, but take a step back for a second and think about this.   

In this case, this implementation violates the single responsibility principle, because you're trying to have `setString` do two different and unrelated things.  It's intention is just to set the text that is passed in, not to modify it.  Adding a comment won't help at all.

Current code in the engine may already have similar issues with methods or classes doing more than they should be; if anything, we should be cleaning up the code to reduce the problem, not add to it.

**Comment by DelinWorks** [comment]
The label pointer seems nice to have...

**Comment by DelinWorks** [comment]
> Current code in the engine may already have similar issues with methods or classes doing more than they should be; if anything, we should be cleaning up the code to reduce the problem, not add to it.

Well if someone is fairly dumb to not realize that the function does two things, then I don't think they should be using a C++ game engine and instead switch to godot gdscript (I have nothing against godot nor gdscript), also we don't want classes to be fat, meaning to have mutiple things that can be packed to a single function. just like `DoThatA`, `DoThatB`, DoThatC` that doesn't feel right. also other game engines like godot stuff multiple functions into one A LOT, so yeah that's what I think of it

**Comment by rh101** [comment]
> Well if someone is fairly dumb to not realize that the function does two things, then I don't think they should be using a C++ game engine and instead switch to godot gdscript

Please avoid making remarks like that, because they never help in any way.

> also we don't want classes to be fat, meaning to have mutiple things that can be packed to a single function. just like `DoThatA`, `DoThatB`, `DoThatC` that doesn't feel elegant, when they're all can be `DoThat` and that's it

I'm definitely not suggesting a class be "fat", completely the opposite in fact.  A class has a specific purpose, and in this suggested implementation, you're quite literally adding something to the class that has nothing to do with it, in essence, making  it "fat".  To be more specific, the label class has one purpose, which is to display text, not to modify it.

I know we think or have feelings about how things are, but that doesn't necessarily mean that our point of view is correct.  Again, I get what you're trying to achieve, but this isn't the way.

**Comment by DelinWorks** [comment]
So what do you think the solution is? make it a singleton and leaving the label class alone? because it's important that having it in cocostudio isn't right

**Comment by rh101** [comment]
> So what do you think the solution is? make it a singleton and leave the label class alone? because it's important that having it in cocostudio isn't right

Cocos Studio is a relic that is still in the code base for, I assume, backwards compatibility.  It's one of the things that eventually need to be addressed, but that doesn't mean it needs to be now.  

Just because Cocos Studio has some code related to localization doesn't mean that code needs to be used, or moved.  It can be left as is, and a new localization support be added elsewhere.



> damn we really need a discord server for this

Discord is the worst place to deal with this.  Having it here means there is a history of the discussion and decisions made.  Discord would be great for asking questions for help with the engine or similar things, but not for stuff like this.

**Comment by DelinWorks** [comment]
> Discord is the worst place to deal with this. Having it here means there is a history of the discussion and decisions made. Discord would be great for asking questions for help with the engine or similar things, but not for stuff like this.

Discord does store discussions you now, and is way better than github from my opinion 

I'll close this PR for now

**Pull request closed without merging**
