### PR TITLE
Feature 803

### PR DESCRIPTION
**Pull request by halx99**
Done #803

The latst   `buildware` apple M1 and android-x64 support are contributed by @pietpukkel, very thanks him.

### CODE REVIEW

**Comment by halx99** [comment]
@pietpukkel The [osx-arm64](https://github.com/axys1/axys/runs/7819651896?check_suite_focus=true) ci failed with:
```txt
/Users/runner/work/axys/axys/build/axys.xcodeproj: error: The linked library 'libbrotlidec.1.0.9.dylib' is missing one or more architectures required by this target: arm64. (in target 'cpp_tests' from project 'axys')
/Users/runner/work/axys/axys/build/axys.xcodeproj: error: The linked library 'libpng16.16.dylib' is missing one or more architectures required by this target: arm64. (in target 'cpp_tests' from project 'axys')
```

I'm not sure does it caused by the action use macos-11

**Comment by pietpukkel** [comment]
I've just synced release 803 and build it from scratch. Gives some deprecation warnings but no errors
Screen Shot 2022-08-13 at 16 18 47
.

**Comment by pietpukkel** [comment]
Why is it linking with libpng16.16.dylib? I thought the project is linked with a static version of the library (as included in thirdparty folder... so it's actually build by ourselves for arm) ? I do not know what libbrotlidec is...  I see no reference or dependency in the Axys project. Strange 🤔

**Comment by halx99** [comment]
The only different between github actions macos vm and your machine

> Why is it linking with libpng16.16.dylib? I thought the project is linked with a static version of the library (as included in thirdparty folder... so it's actually build by ourselves for arm) ? I do not know what libbrotlidec is... I see no reference or dependency in the Axys project. Strange 🤔

Maybe it's cross compile issue? bacause the github action macos vm host architecture is `x86_64`

**Comment by pietpukkel** [comment]
I tried to build via the commandline as well (cmake --build build --config Release --target cpp_tests -- -quiet).  Was also successfull.

**Comment by pietpukkel** [comment]
> Maybe it's cross compile issue? bacause the github action macos vm host architecture is `x86_64`

I do not think so. But let me try on my intel mac too.

**Comment by pietpukkel** [comment]
> Maybe it's cross compile issue? bacause the github action macos vm host architecture is `x86_64`

Yes it seems to be... I'll try to figure out what is the issue and get back to you (I get other errors on my Intel mac).

**Comment by halx99** [comment]
> > Maybe it's cross compile issue? bacause the github action macos vm host architecture is `x86_64`
> 
> Yes it seems to be... I'll try to figure out what is the issue and get back to you (I get other errors on my Intel mac).

OK

**Comment by pietpukkel** [comment]
And it builds on my Intel Mac too.  The issue seems to be with some cmake files that look for certain frameworks. If they are present, then they are included. The CMake does not check architecure compatibility.  My best guess is that the two frameworks that now are missing in your case are included by the freetype cmake file.

The make for ARM on your VM should be with options FT_DISABLE_PNG and FT_DISABLE_BROTLI (in my case also with FT_DISABLE_HARFBUZZ).

Screenshot 2022-08-13 at 18 21 29

**Comment by halx99** [comment]
Good, I will try it

**Comment by halx99** [comment]
works known

**Comment by pietpukkel** [comment]
Nice! So Axys now supports Apple Silicon out of the box  😁

**Comment by halx99** [comment]
Yeah!

**Pull request merged**
